### ISSUE TITLE
What’s the best practice for learning and Writing Unit Test?

### ISSUE THREAD

**Issue by MoElnaggar14** [ahmedk92/QandA#1]
I know it’s a common question but i’m confusing about it. 
FYI: i’m working on old Project with a legacy code

**Comment by ahmedk92** [comment]
I don't think I'm qualified to talk about "best practices" about this subject, but I'll write what I know.

Unit tests need to be:
1. Isolated
2. Short
3. Fast (when executed)
4. Reliable (not flaky)

The quality of tests reflect your code's quality. 

#### Isolation
Keep your classes separate. Avoid direct dependencies using concrete type references, and instead use protocols for example, or closures for passing methods.

#### Shortness
Keep your units functions/classes short and to the point. 

You can already see how these relate to SOLID principles.

#### Speed And Reliability
UI and I/O are the major speed and reliability bottlenecks for mobile apps. Popular architecture patterns (MVVM, MVP, ..etc) help in testing your logic while avoiding instantiating UI by extracting that logic from view controllers to view models, presenters, interactions, ...etc.

You can avoid doing actual I/O by (again) leveraging protocols and closures to abstract I/O code (e.g. network, databases, ...etc) so that you can mock these dependencies in unit tests. This is essentially what separates unit tests from [integration tests](https://martinfowler.com/articles/practical-test-pyramid.html). You don't want to bother with network failing or database errors.

Some argue the last point especially with local I/O (databases). Some see it's better to really access databases in unit tests, albeit databases dedicated for tests. I actually go with this approach, as long as using real databases doesn't hinder test execution that much.

### Legacy Code
Indeed it's painful to refactor and write tests for legacy code. However, you can start with new code you add. Separating new code in separate modules can help. That way it's easier to write tests for it, and may actually reuse it if there ever be a rewrite. Eventually you're going to integrate with the legacy codebase, or even delve inside that code. This is your chance to refactor on the go. Don't get distracted with low coverage metrics. It's better late than never.

**Comment by MoElnaggar14** [comment]
I so grateful for your answer

**Comment by ahmedk92** [comment]
I see relevant questions on learning resources too. I recommend [this repo](https://github.com/oleh-zayats/unit-testing-swift/blob/master/README.md); it has a nice compilation of articles and videos.
